name: Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get composer cache directory
        id: composer_config
        uses: baschny/php-composer-action@v1
        with:
          composer_version: 2.4
          command: get_config

      - name: Cache composer downloads
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer_config.outputs.composer_cache_dir }}
          key: composer-v${{ steps.composer_config.outputs.composer_major_version }}

      - name: Run composer install
        uses: baschny/php-composer-action@v1
        with:
          composer_version: 2.4
          command: install

      - name: Deployment
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SECRET_HOST }}
          username: ${{ secrets.SECRET_USER }}
          key: ${{ secrets.SECRET_KEY }}
          overwrite: true
          source: "*, !node_modules"
          target: "vrisc.ru"
